DEVC-1128: Created landing page, profile form and modal for displaying devon instances
devonfw-forge/devcon-electron pull request #30
Opened 2020-08-13 06:57 UTC by suprishi

2020-08-13 13:00 UTC, jambulud requested changes
Rename the files and folders
Instead of CamelCase use snake-case

2020-08-13 13:00 UTC, jambulud commented on main/index.ts
> +
Can you extract this to another file/files?

2020-08-13 13:00 UTC, jambulud commented on renderer/modules/intro/components/LandingPage/IdeDialog.tsx
> +});
Extract this to another file

2020-08-13 13:00 UTC, jambulud commented on renderer/modules/intro/components/LandingPage/IdeDialog.tsx
> +        </List>
Move to a separated component

2020-08-13 13:00 UTC, jambulud commented on renderer/modules/intro/components/LandingPage/IdeDialog.tsx
> +        </p>
move to another component

2020-08-13 13:00 UTC, jambulud commented on renderer/modules/intro/components/LandingPage/LandingPage.tsx
> +});
Move to another file
landing-page.styles.ts

2020-08-13 13:00 UTC, jambulud commented on renderer/modules/intro/components/ProfileSetup/ProfileSetup.tsx
> +})(TextField);
Move to another file
profile-setup.styles.ts

2020-08-13 13:00 UTC, jambulud commented on renderer/modules/intro/components/ToolbarContainer/ToolbarContainer.tsx
> +    });
Move to another file

2020-08-13 13:00 UTC, jambulud commented on renderer/modules/intro/components/ProfileSetup/ProfileSetup.tsx
> +        </Button>
Couldn't each form control be a separated component? 

Each component would receive at least one function (from props) that is executed when the field is resolved?

```tsx
componentForm() {
  const [fields, setFields] = useState({ field1: false, field2: false}) // true if its filled and validated

  const resolveField = (fieldUpdate: { [key: string]: boolean}) => {
    return () =>
      setFields((prevState) => ({
        ...prevState,
        ...fieldUpdate,
      }));
  }

  return (
    <form>
      <FieldComponent1 onResolve={resolveField({ field1: true })}></FieldComponent1>
      <FieldComponent2 onResolve={resolveField({ field2: true })}></FieldComponent2> 
      <Button disabled={fields.values().every((resolved) => resolved)}>Submit form</Button>
    </form>
  )
}

```

2020-08-13 13:09 UTC, suprishi commented on renderer/modules/intro/components/ProfileSetup/ProfileSetup.tsx
> +        </Button>
Doable. But what does it achieve? Is it for better maintainability or somehow improves performance as well?

2020-08-13 13:15 UTC, jambulud commented on renderer/modules/intro/components/ProfileSetup/ProfileSetup.tsx
> +        </Button>
Maintanability and readability

When you  have lots of nested tags it is difficult to keep track of what you are reading. Also, isolating smaller components allows you to do modifications in one single formControl (in this case) being sure that you don't break the rest of the form

2020-08-13 13:37 UTC, suprishi commented on main/index.ts
> +
Shall I move them to a new `profile-setup` directory under `main/modules/`

2020-08-13 13:39 UTC, jambulud commented on main/index.ts
> +
Yes, seems to be a good place

2020-08-14 12:56 UTC, jambulud approved these changes

2020-08-14 12:56 UTC, merged